// OpalHedgeDiagnosticErrorCode.swift

enum OpalHedgeDiagnosticErrorCode {
    static let unknown = "unknown"
    static let contractConstraintValidationFailed = "contract.constraint_validation_failed"
    static let dataDocumentInvalidJson = "data_document.invalid_json"
    static let dataDocumentInvalidRootObject = "data_document.invalid_root_object"
    static let dataDocumentMissingField = "data_document.missing_field"
    static let dataDocumentInvalidFieldType = "data_document.invalid_field_type"
    static let dataDocumentInvalidContractSide = "data_document.invalid_contract_side"
    static let dataDocumentInvalidSettlementType = "data_document.invalid_settlement_type"
    static let oracleInvalidHexLength = "oracle.invalid_hex_length"
    static let oracleInvalidHexCharacter = "oracle.invalid_hex_character"
    static let oracleInvalidMessageLength = "oracle.invalid_message_length"
    static let oracleInvalidScriptInteger = "oracle.invalid_script_integer"
    static let oracleInvalidPrice = "oracle.invalid_price"
    static let oracleInvalidPublicKey = "oracle.invalid_public_key"
    static let oracleInvalidSignature = "oracle.invalid_signature"
    static let oracleInvalidDigest = "oracle.invalid_digest"
    static let oracleCryptographyFailure = "oracle.cryptography_failure"
    static let bitcoinCashInvalidRedeemScriptHex = "bitcoin_cash.invalid_redeem_script_hex"
    static let bitcoinCashInvalidScriptHashByteCount = "bitcoin_cash.invalid_script_hash_byte_count"
    static let bitcoinCashScriptDataPushTooLarge = "bitcoin_cash.script.data_push_too_large"
    static let bitcoinCashParameterInvalidHex = "bitcoin_cash.parameter.invalid_hex"
    static let bitcoinCashParameterInvalidCompressedPublicKey = "bitcoin_cash.parameter.invalid_compressed_public_key"
    static let bitcoinCashParameterInvalidLockScript = "bitcoin_cash.parameter.invalid_lock_script"
    static let bitcoinCashParameterInvalidPositiveInteger = "bitcoin_cash.parameter.invalid_positive_integer"
    static let bitcoinCashParameterInvalidNonnegativeInteger = "bitcoin_cash.parameter.invalid_nonnegative_integer"
    static let bitcoinCashParameterInvalidBooleanInteger = "bitcoin_cash.parameter.invalid_boolean_integer"
    static let transactionHashInvalid = "bitcoin_cash.transaction_hash.invalid"
    static let fundingAlreadyExists = "funding.already_exists"
    static let fundingOutputInvalidPayoutSatoshis = "funding.output.invalid_payout_satoshis"
    static let fundingOutputInvalidDustReserveSatoshis = "funding.output.invalid_dust_reserve_satoshis"
    static let fundingOutputSatoshisOverflow = "funding.output.satoshis_overflow"
    static let fundingRecordInvalid = "funding.record_invalid"
    static let settlementConditionInvalid = "settlement.condition_invalid"
    static let settlementPayoutInvalid = "settlement.payout_invalid"
    static let settlementRecordInvalid = "settlement.record_invalid"
}
